services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./api:/app:cached
    command: air
    ports:
      - "8080:8080"

  db:
    image: postgres:17.0-bookworm
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db-data:
