version: "3.8"

volumes:
  postgres-data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
